// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO2alS97qhF4b6g6Q31Wwhz9fSTY2oE-k',
    appId: '1:816593150639:android:dcd716aae148aaa942aa5a',
    messagingSenderId: '816593150639',
    projectId: 'mobile-architechture',
    storageBucket: 'mobile-architechture.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwuBlggkSzfgEFiA4cqQzq7Jw8toeMp_Q',
    appId: '1:816593150639:ios:394abf2531b0f54f42aa5a',
    messagingSenderId: '816593150639',
    projectId: 'mobile-architechture',
    storageBucket: 'mobile-architechture.firebasestorage.app',
    iosBundleId: 'mn.nexusinfinity.rebox',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBmpatQz5_kxrERv1TPEC-U1OKUs0XWQM',
    appId: '1:816593150639:web:11eef4ca60d23f9f42aa5a',
    messagingSenderId: '816593150639',
    projectId: 'mobile-architechture',
    authDomain: 'mobile-architechture.firebaseapp.com',
    storageBucket: 'mobile-architechture.firebasestorage.app',
    measurementId: 'G-Z1WNFMCYSQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwuBlggkSzfgEFiA4cqQzq7Jw8toeMp_Q',
    appId: '1:816593150639:ios:394abf2531b0f54f42aa5a',
    messagingSenderId: '816593150639',
    projectId: 'mobile-architechture',
    storageBucket: 'mobile-architechture.firebasestorage.app',
    iosBundleId: 'mn.nexusinfinity.rebox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBmpatQz5_kxrERv1TPEC-U1OKUs0XWQM',
    appId: '1:816593150639:web:e90ef57e2e4b07a242aa5a',
    messagingSenderId: '816593150639',
    projectId: 'mobile-architechture',
    authDomain: 'mobile-architechture.firebaseapp.com',
    storageBucket: 'mobile-architechture.firebasestorage.app',
    measurementId: 'G-XG8JPQ7BQE',
  );

}